export enum Constants {
  NO_SPAN_METADATA = 'DATADOG_NO_SPAN_METADATA',
  SPAN_METADATA = 'DATADOG_SPAN_METADATA',
  SPAN_METADATA_ACTIVE = 'DATADOG_SPAN_METADATA_ACTIVE',
  TRACE_INJECTORS = 'DATADOG_TRACE_INJECTORS',
}
